resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/IvanChalukov/concourse-tasks.git
    branch: task-4
    git_config:
    - name: safe.directory
      value: /tmp/build/get

- name: every-5min
  type: time
  icon: clock-outline
  source:
    interval: 300s

jobs:
- name: docker-pipeline-job
  plan:
  - get: every-5min
    trigger: true
  - get: scripts
    trigger: true
  - task: docker-pipeline-task
    config:
      platform: linux
      image_resource:
        source:
          repository: ichalukov/sample_image
          tag: latest
        type: registry-image
      inputs:
      - name: scripts
      run:
        path: scripts/print.sh