resources:
- name: scripts
  type: git
  source:
    uri: git@github.com:IvanChalukov/concourse-tasks.git
    branch: task-5
    icon: github
    private_key: ((private_key))
    git_config:
    - name: safe.directory
      value: '*'

- name: every-5min
  type: time
  icon: clock-outline
  source:
    interval: 300s

jobs:
- name: docker-pipeline-job
  plan:
  - get: every-5min
    trigger: true
  - get: scripts
    trigger: true
  - task: docker-pipeline-task
    config:
      platform: linux
      image_resource:
        source:
          repository: ichalukov/sample_image
          tag: latest
        type: registry-image
      inputs:
      - name: scripts
      outputs:
      - name: scripts
      run:
        path: /bin/sh
        args:
        - -c
        - |
          cd scripts
          ./print.sh
          git config --global --add safe.directory "*"
          git config --global user.email "ichalukov@gmail.com"
          git config --global user.name "Ivan Chalakov"
          if ! git diff --quiet; then
            git commit -am "Update greeted.txt"
          else
            echo "No changes to commit."
          fi
  - put: scripts
    params:
      repository: scripts