---
jobs:
- name: hello-sap-job
  public: true
  plan:
  - task: hello-sap-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello SAP"]